### ISSUE TITLE
Wishlist item: Next meetup banner "above the fold" on the home page.

### ISSUE THREAD

**Issue by dbernar1** [yagudaev/winnipegjs#13]
It might be nice to move the "next meetup" banner above the fold - it's below the fold on my screen anyway...

I can volunteer to do a pull request for this if we wanna do this. I like the way it looks if I move that banner under the logo.

**Comment by pbraun** [comment]
I think that's a good idea :-) many people don't have high res screens.

**Comment by dbernar1** [comment]
Great i will make a pull request if no one else does..

## 

Dan Bernardic
My contact information is at http://gravatar.com/dbernar1

**Comment by yagudaev** [comment]
Yeah that sounds good :). Reference this issue in your PR too.
