### ISSUE TITLE
Suggested topics

### ISSUE THREAD

**Issue by dbernar1** [yagudaev/winnipegjs#9]
Good morning!

I'd like to develop functionality that would allow users to offer topics they would like to talk about, or hear someone talk about.

Would you guys be interested in adding that functionality to winnipegjs.com?

Thanks!

**Comment by dbernar1** [comment]
I see that there is a uservoice widget actually on the website. Didn't notice it until now.

Is there reason to replace uservoice with our own functionality? Otherwise, let's close this issue.

**Comment by yagudaev** [comment]
Closing as there is no reason for that. The only thing maybe is to also add it to the homepage and call it "Suggest a Topic".
